apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack
  namespace: kube-ops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-ops
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/NoSpof/kubernetes_bootstrap
    targetRevision: main