apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  tenantsbootstrap
  namespace: {{ .Values.spec.destination.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: teambootstraping
  source:
    path: .
    repoURL: https://github.com/NoSpof/Tenants_bootstrap
    targetRevision: {{ .Values.env }}
    helm:
      valuesFiles:
      - common-values.yaml
      - {{ .Values.env }}-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
